/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package MainPackage;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author chait
 */
public class FormPanel extends javax.swing.JPanel {

    /**
     * Creates new form formPanel
     */
    JPanel bottomPanel;
    private String imagePath;

    public FormPanel(JPanel bottomPanel) {
        initComponents();
        

        this.bottomPanel = bottomPanel;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioButtonGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        firstNameValue = new javax.swing.JTextField();
        onSubmit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        photoUploadButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        messageValue = new javax.swing.JTextArea();
        otherRadioButton = new javax.swing.JRadioButton();
        femaleRadioButton = new javax.swing.JRadioButton();
        maleRadioButton = new javax.swing.JRadioButton();
        lastNameValue = new javax.swing.JTextField();
        patientTypeDropDown = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        emailValue = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ageValue = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PATIENT FORM");

        jLabel2.setText("First Name");

        firstNameValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameValueActionPerformed(evt);
            }
        });
        firstNameValue.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                firstNameValueKeyPressed(evt);
            }
        });

        onSubmit.setText("SUBMIT");
        onSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onSubmitActionPerformed(evt);
            }
        });

        jLabel3.setText("Last Name");

        photoUploadButton.setText("Upload");
        photoUploadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                photoUploadButtonActionPerformed(evt);
            }
        });

        messageValue.setColumns(20);
        messageValue.setRows(5);
        jScrollPane1.setViewportView(messageValue);

        radioButtonGroup.add(otherRadioButton);
        otherRadioButton.setText("others");
        otherRadioButton.setActionCommand("OTHERS");

        radioButtonGroup.add(femaleRadioButton);
        femaleRadioButton.setText("Female");
        femaleRadioButton.setActionCommand("FEMALE");
        femaleRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleRadioButtonActionPerformed(evt);
            }
        });

        radioButtonGroup.add(maleRadioButton);
        maleRadioButton.setText("Male");
        maleRadioButton.setActionCommand("MALE");
        maleRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleRadioButtonActionPerformed(evt);
            }
        });

        lastNameValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameValueActionPerformed(evt);
            }
        });
        lastNameValue.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lastNameValueKeyPressed(evt);
            }
        });

        patientTypeDropDown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acute Patient", "Chronic Patient", "Pediatric Patient", "Geriatric Patient", "Emergency Patient", "Surgical Patient", "Psychiatric Patient", "Rehabilitation Patient" }));
        patientTypeDropDown.setSelectedIndex(4);
        patientTypeDropDown.setToolTipText("");
        patientTypeDropDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientTypeDropDownActionPerformed(evt);
            }
        });

        jLabel5.setText("Gender");

        jLabel6.setText("Message");

        jLabel7.setText("Email");

        jLabel8.setText("Patient Type");

        jLabel9.setText("Photo");

        emailValue.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                emailValueKeyPressed(evt);
            }
        });

        jLabel4.setText("Age");

        ageValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageValueActionPerformed(evt);
            }
        });
        ageValue.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ageValueKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(patientTypeDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(maleRadioButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(femaleRadioButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(otherRadioButton))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(photoUploadButton)
                                    .addComponent(emailValue, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lastNameValue, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(firstNameValue, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ageValue, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel5))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(332, 332, 332))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addComponent(onSubmit))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(273, 273, 273)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(firstNameValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lastNameValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ageValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(emailValue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(femaleRadioButton)
                        .addComponent(maleRadioButton)
                        .addComponent(otherRadioButton)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(patientTypeDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(photoUploadButton)
                    .addComponent(jLabel9))
                .addGap(29, 29, 29)
                .addComponent(onSubmit)
                .addContainerGap(105, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void radioButtonFieldValidation(){
        try{
            if (radioButtonGroup.getSelection().toString()== null ||radioButtonGroup.getSelection().toString().isEmpty()){
                throw new Exception();
            }
        }
        
        catch (Exception e){
            JOptionPane.showMessageDialog(this,"Gender is not selected, please choose the gender","Validation Error",JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void messageTextBoxValidation(){
        try{
            if (messageValue.getText()== null ||messageValue.getText().isEmpty()){
                throw new IllegalArgumentException("Please provide your past medical history");
            }
        }
        
        catch (IllegalArgumentException e){
            JOptionPane.showMessageDialog(this,e.getMessage(),"Validation Error",JOptionPane.ERROR_MESSAGE);
        }
    }
    private void firstNameValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameValueActionPerformed
    
//    public void firstNameValidation(){
//        if firs
//    }
    private void onSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onSubmitActionPerformed
        // TODO add your handling code here:
        
        
        ImageIcon icon = new ImageIcon(imagePath);
        Image image = icon.getImage().getScaledInstance(150, 150, Image.SCALE_DEFAULT);
        ImageIcon scaledIcon = new ImageIcon(image);
        
        User user = new User();
        if (firstNameValue.getText() == null || firstNameValue.getText().isEmpty() || lastNameValue.getText() == null || lastNameValue.getText().isEmpty() || ageValue.getText() == null || ageValue.getText().isEmpty() || emailValue.getText() == null || emailValue.getText().isEmpty() || imagePath == null || imagePath.isEmpty()) {
 
            JOptionPane.showMessageDialog(this, "Please provide all the values mentioned in the form and upload the image", "Form Error", JOptionPane.ERROR_MESSAGE);        
            
        }
        else{
            
   
            user.setFirstName(firstNameValue.getText());
            user.setLastName(lastNameValue.getText());
            user.setAge(ageValue.getText());
            user.setEmail(emailValue.getText());
            radioButtonFieldValidation();
            user.setGender(radioButtonGroup.getSelection().getActionCommand());
            user.setPatientType(patientTypeDropDown.getSelectedItem().toString());
            messageTextBoxValidation();
            user.setMessage(messageValue.getText());
                
          
        }
        
        
        
        ViewPanel viewObject = new ViewPanel(user,bottomPanel,scaledIcon);
        bottomPanel.add(viewObject);
        CardLayout layout = (CardLayout) this.bottomPanel.getLayout();
        layout.next(bottomPanel);
       
        
    }//GEN-LAST:event_onSubmitActionPerformed

    private void lastNameValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameValueActionPerformed

    private void patientTypeDropDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientTypeDropDownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientTypeDropDownActionPerformed

    private void maleRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleRadioButtonActionPerformed

    private void femaleRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleRadioButtonActionPerformed

    private void ageValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageValueActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_ageValueActionPerformed

    private void ageValueKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ageValueKeyPressed
        // TODO add your handling code here:
        
        try{
            
            int age = Integer.parseInt(ageValue.getText());
            
            ageValue.setForeground(Color.black);
            
        }
        catch(Exception e){
            
            ageValue.setForeground(Color.red);

        }
    }//GEN-LAST:event_ageValueKeyPressed

    private void emailValueKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailValueKeyPressed
        // TODO add your handling code here:
         try{
             
             if (emailValue.getText().matches("^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$")){
                 
                 emailValue.setForeground(Color.black);

            }
            
            else{
                throw new Exception();
            }
                        
        }
        catch(Exception e){
            
            emailValue.setForeground(Color.red);

        }
    }//GEN-LAST:event_emailValueKeyPressed

    private void photoUploadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_photoUploadButtonActionPerformed
        // TODO add your handling code here:
        
        JFileChooser fileChooser = new JFileChooser();
        int result = fileChooser.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            imagePath = selectedFile.getAbsolutePath();
            
        }
    }//GEN-LAST:event_photoUploadButtonActionPerformed

    private void firstNameValueKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_firstNameValueKeyPressed
        // TODO add your handling code here:
        
        try{
             
             if (firstNameValue.getText().matches("^[A-Za-z][a-zA-Z ]+$")){
                 
                 firstNameValue.setForeground(Color.black);

            }
            
            else{
                throw new Exception();
            }
                        
        }
        catch(Exception e){
            
            firstNameValue.setForeground(Color.red);

        }
    }//GEN-LAST:event_firstNameValueKeyPressed

    private void lastNameValueKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lastNameValueKeyPressed
        // TODO add your handling code here:
        
        try{
             
             if (lastNameValue.getText().matches("^[A-Za-z][a-zA-Z ]+$")){
                 
                 lastNameValue.setForeground(Color.black);

            }
            
            else{
                throw new Exception();
            }
                        
        }
        catch(Exception e){
            
            lastNameValue.setForeground(Color.red);

        }
    }//GEN-LAST:event_lastNameValueKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ageValue;
    private javax.swing.JTextField emailValue;
    private javax.swing.JRadioButton femaleRadioButton;
    private javax.swing.JTextField firstNameValue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastNameValue;
    private javax.swing.JRadioButton maleRadioButton;
    private javax.swing.JTextArea messageValue;
    private javax.swing.JButton onSubmit;
    private javax.swing.JRadioButton otherRadioButton;
    private javax.swing.JComboBox<String> patientTypeDropDown;
    private javax.swing.JButton photoUploadButton;
    private javax.swing.ButtonGroup radioButtonGroup;
    // End of variables declaration//GEN-END:variables
}
